public final class HtmlConstants {
    public static final String OPENING = 
              "<html>\n"
            + "  <head>\n"
            + "    <meta http-equiv=\"content-type\" content=\"text/html; "
            + "charset=UTF-8\">\n"
            + "  </head>\n"
            + "  <body bgcolor=\"#FFFFFF\" text=\"#000000\">\n"
            + "    <br>\n"
            + "    <div>\n"
            + "      <div>\n"
            + "        <center>\n"
            + "          <div style=\"word-wrap:break-word\">\n"
            + "            <table style=\"border:none;width:600px;color:"
            + "rgb(85,85,85);font-family:Optima,\'Trebuchet MS\',sans-serif\" "
            + "border=\"0\" width=\"600\">\n"
            + "              <tbody>\n                <tr>\n"
            + "                  <td style=\"padding:10px 20px;vertical-align:"
            + "top;width:auto;text-align:justify;font-size:10pt\">";
    public static final String AFTER_DATE = 
              "</td>\n"
            + "                </tr>\n"
            + "                <tr>\n"
            + "                  <td style=\"padding:10px 20px;vertical-align:"
            + "middle;width:auto;text-align:justify;font-size:26pt;margin:0px\""
            + "><img src=\"compclub-logo.png\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"
            + "&nbsp;&nbsp;Computing Club Events</td>"
            + "                </tr>\n"
            + "              </tbody>\n"
            + "            </table>\n";
    public static final String CONTENT_START = 
              "            <table style=\"border:none;width:600px;table-layout"
            + ":fixed;color:rgb(85,85,85);font-family:Optima,'Trebuchet MS',"
            + "sans-serif\" border=\"0\" width=\"600\">\n"
            + "              <tbody>\n"
            + "                <tr>\n"
            + "                  <td style=\"padding:10px 20px;vertical-align:"
            + "top;width:auto;text-align:justify;font-size:12pt\">\n";
    public static final String CONTENT_TITLE = 
              "                    <p style=\"text-align:center;color:rgb"
            + "(17,17,17);font-size:24pt;margin:10px 0px\">title</p>\n";
    public static final String CONTENT_IMG = 
              "                    <div style=\"width:556px;min-height:10px;"
            + "text-align:center;vertical-align:middle;background-repeat:"
            + "initial initial\"><img src=\"cid:image\"></div>\n";
    public static final String CONTENT_LINK = 
              "                    <div style=\"text-align:right;font-size:20px"
              + "\"><a href=\"link\">lnk-txt &rarr;</a></div>\n";
    public static final String CONTENT_END = 
              "                  </td>\n"
            + "                </tr>\n"
            + "              </tbody>\n"
            + "            </table>\n";
    public static final String SPONSOR_TITLE =
              "                <table style=\"border:none;width:600px;color:rgb"
            + "(85,85,85);font-family:Optima,'Trebuchet MS',sans-serif\" "
            + "border=\"0\" width=\"600\">\n"
            + "                  <tbody>\n"
            + "                    <tr>\n"
            + "                      <td style=\"padding:10px 20px;vertical"
            + "-align:middle;width:auto;text-align:justify;font-size:26pt;"
            + "margin:0px\">&nbsp;Other Events and Promotions</td>\n"
            + "                    </tr>\n"
            + "                  </tbody>\n"
            + "                </table>\n";
    public static final String ENDING =
              "            <table style=\"border:none;width:600px;color:rgb"
            + "(85,85,85);font-family:Optima,'Trebuchet MS',sans-serif\" "
            + "border=\"0\" width=\"600\">\n"
            + "              <tbody>\n"
            + "                <tr>\n"
            + "                  <td style=\"padding:10px 20px;vertical-align:"
            + "top;width:auto;text-align:justify;font-size:12pt\">\n"
            + "                    <p style=\"color:rgb(17,17,17);font-size:"
            + "24pt;margin:10px 0px\">Contact Us</p>\n"
            + "                    <p>Computing 1, 13 Computing Drive, "
            + "Singapore 117417</p>\n"
            + "                    <p><a href=\"mailto:connect@nuscomputing."
            + "com\" style=\"color:rgb(34,118,244);text-decoration:none\" "
            + "target=\"_blank\">connect@nuscomputing.com</a>\n"
            + "                    </p>\n"
            + "                  </td>\n"
            + "                  <td style=\"padding:10px 20px;vertical-align:"
            + "middle;width:100px;text-align:justify\"><img src=\"cid:longcat-"
            + "back\"></td>\n"
            + "                </tr>\n"
            + "              </tbody>\n"
            + "            </table>\n"
            + "            <table style=\"border:none;width:600px;color:rgb"
            + "(85,85,85);font-family:Optima,'Trebuchet MS',sans-serif\" "
            + "border=\"0\">\n"
            + "              <tbody>\n"
            + "                <tr>\n"
            + "                  <td style=\"padding:10px 20px;vertical-align:"
            + "top;width:auto;text-align:justify\">\n"
            + "                  </td>\n"
            + "                </tr>\n"
            + "              </tbody>\n"
            + "            </table>\n"
            + "          </div>\n"
            + "        </center>\n"
            + "      </div>\n"
            + "      <br>\n"
            + "    </div>\n"
            + "    <br>\n"
            + "    <br>\n"
            + "  </body>\n"
            + "</html>\n";
}
